# Generated by Django 6.0.1 on 2026-03-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('note', 'Note'), ('checklist', 'Checklist')], default='note', max_length=20),
        ),
    ]
