# Generated by Django 6.0.1 on 2026-03-15 03:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_note_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'is_deleted', 'is_archived', 'is_pinned', '-created_at'], name='note_home_list_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'is_deleted', 'deleted_at'], name='note_trash_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'is_archived', 'is_deleted', '-created_at'], name='note_archive_idx'),
        ),
    ]
