# Generated by Django 6.0.1 on 2026-04-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_note_home_list_idx_note_note_trash_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
