# Generated by Django 6.0.1 on 2026-06-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteimage',
            name='ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
