# Generated by Django 6.0.1 on 2026-06-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_noteimage_ocr_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteimage',
            name='ocr_text',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
